# config.yaml

# Absolute path to the genome fasta file
ref: " "
annotation: " "

# Fastq file suffix
fastq_suffix: " " # Defualt is ".fq.gz"

# Fastp parameters
qualified_quality_phred: 20
unqualified_percent_limit: 40
trim_front: 10

# Featurecounts parameters
feature_type: "exon"
attribution: "gene_id"

# Sample list
sample:
